### ISSUE TITLE
If Dynamic URL and field is empty

### ISSUE THREAD

**Issue by dbloch3643** [krypu/azure-devops-extension-url-field#1]
The extension is exactly what I was looking for, only small tweak would be:

Using scenario 2 "A dynamic URL that combines a static base URL with some parameters taken from an other field", if the field being used for building the URL is empty/blank, it would be nice if no URL was generated.  Or an option to make it not generator if field is empty.

**Comment by krypu** [comment]
Hi, thank you for a kind review.

This looks like a good idea. I will try to add this soon, once I get some spare time.

**Comment by dbloch3643** [comment]
Excellent, thank you for implementing the change.  Already in our production environment..
