### ISSUE TITLE
Scenario 3 Not Working

### ISSUE THREAD

**Issue by kupdegrove** [krypu/azure-devops-extension-url-field#3]
Despite leaving only {field} as the URL parameter, when I build from a text field where I paste a link to a file, it simply does nothing.  I've even tried a very simple www.google.com in the text field as well as http://www.google.com.  

Nada.

**Comment by krypu** [comment]
Hi, please make sure you use http:// or file:// (for a local machine file) in the field where you provide value. As of now, it is necessary.

If you cannot and have a more advanced scenario, please give me a few more details about the file and a link you want to have.

**Comment by krypu** [comment]
Thank you for the information, I have replicated the bug, so time to fix it.

**Comment by krypu** [comment]
Hello! I was able to replicate the issue, but only when missing either http:// or file:// or at least bare //.

Can you please double check the case with a protocol prefix? Something like:

URL = {field}
Title -> any value
Field -> any string field
Field value on a work item form = //google.com

**Comment by kupdegrove** [comment]
Thank you for the quick reply. In my case it was an ID10T error…LOL. I forgot to switch to the correct source field in the control. Once I corrected that, it worked like a charm. It’s an excellent control and fills a much needed gap.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by krypu** [comment]
I'm glad it's working for you now. I would appreciate a rating and a short review on VS marketplace.
